In [468]:
!pip3 install -U ucimlrepo 

In [469]:
irisDataset = fetch_ucirepo("Iris",)

In [595]:
import numpy as np

xTrainForSetsuta = np.array(irisDataset.data.features)

# Since we are dealing with strings as our target type, we must convert into integers, and binary.
# In particular Iris-setosa and Iris-versicolor will be identified as 0 and Iris-virginica will be 1.
# If the model predicts 1 we know it is an Iris-viginica, if it is a 0, we use a second model to conduct
# binary logistic regression again on the last two Iris species.

yTrainBeforeBinaryConversion = np.array(irisDataset.data.targets)

wForSetsuta = np.ones(4)

bForSetsuta = 1

wForVersicolor = np.ones(4)

bForVersicolor = 1

lambda_Setsuta = 0.1

lambda_Versicolor = 0.1

learningRateAlphaSetsuta = 0.01

learningRateAlphaVersicolor = 0.01

numIterations = 10000
print(xTrainForSetsuta)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.1 1.5 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [596]:
# Binary conversion for Setsuta target dataset
yTrainForSetsuta = np.zeros((yTrainBeforeBinaryConversion.shape[0]))
for i in range(yTrain.shape[0]):
    if yTrainBeforeBinaryConversion[i] == 'Iris-versicolor' or 'Iris-virginica':
        yTrainForSetsuta[i] = 0
    if yTrainBeforeBinaryConversion[i] == 'Iris-setosa':
        yTrainForSetsuta[i] = 1
        
# Binary conversion for Versicolor target dataset
xTrainForVersicolor = xTrainForSetsuta[50:151]
yTrainForVersicolorString = yTrainBeforeBinaryConversion[50:151]
yTrainForVersicolorBinary = np.zeros(yTrainForVersicolorString.shape[0])
for i in range(yTrainForVersicolorString.shape[0]):
    if yTrainForVersicolorString[i] == 'Iris-versicolor':
        yTrainForVersicolorBinary[i] = 1
    if yTrainForVersicolorString[i] == 'Iris-virginica':
        yTrainForVersicolorBinary[i] = 0

In [603]:
def computeGradients(xTrain, yTrain, w, b, lambda_):
    
    derivativeW = np.zeros(w.shape[0])
    derivativeB = 0
    
    for i in range(xTrain.shape[0]):
        z = (np.dot(xTrain[i],w) + b)
        f_x = (1 / (1 + np.exp(-1 * z)))
        f_x -= yTrain[i]
        for j in range(xTrain.shape[1]):
            derivativeW[j] = derivativeW[j] + (f_x * xTrain[i, j])
        derivativeB = derivativeB + f_x
    derivativeW = derivativeW/(xTrain.shape[1])
    derivativeB = derivativeB/(xTrain.shape[1])
    
    for i in range(xTrain.shape[1]):
        derivativeW[i] = (derivativeW[i] + ((lambda_/xTrain.shape[0]) * w[i]))
    return derivativeW, derivativeB

In [624]:
def gradientDescent(xTrain, yTrain, w, b, lambda_, learningRateAlpha, numIterations):
    
    for i in range(numIterations):
        derivativeW, derivativeB = computeGradients(xTrain, yTrain, w, b, lambda_)
        w = (w - (learningRateAlpha * derivativeW))
        b = (b - (learningRateAlpha * derivativeB))
    return w, b

In [633]:
# Train setsota model
wForSetsuta, bForSetsuta = gradientDescent(xTrainForSetsuta, yTrainForSetsuta, wForSetsuta, bForSetsuta, lambda_Setsuta, learningRateAlphaSetsuta, numIterations)

# Train versicolor model
wForVersicolor, bForVersicolor = gradientDescent(xTrainForVersicolor, yTrainForVersicolorBinary, wForVersicolor, bForVersicolor, lambda_Versicolor, learningRateAlphaVersicolor, numIterations)

In [634]:
def irisDecision(wForSetsuta, bForSetsuta, wForVersicolor, bForVersicolor, XFeatures):
    
    decision = ""
    
    z = np.dot(XFeatures, wForSetsuta) + bForSetsuta
    f_x = (1 / (1 + np.exp(-1 * z)))
    if f_x >= 0.5:
        decision = "Iris-setsuta" + " precision: " + str(int(1000 * f_x)/10)
    if f_x < 0.5:
        z = np.dot(XFeatures, wForVersicolor) + bForVersicolor
        f_x = (1 / (1 + np.exp(-1 * z)))
        if f_x >= 0.5:
            decision = "Iris-versicolor" + " precision: " + str(int(1000 * f_x)/10)
        if f_x < 0.5:
            decision = "Iris-virginica" + " precision: " + str(int(1000 * (1 - f_x))/10)
    return decision

In [635]:
irisDecision(wForSetsuta, bForSetsuta, wForVersicolor, bForVersicolor, [6.5,3.,5.2,2.])

'Iris-virginica precision: 98.7'

In [636]:
for i in range(xTrainForSetsuta.shape[0]):
    print(irisDecision(wForSetsuta, bForSetsuta, wForVersicolor, bForVersicolor, xTrainForSetsuta[i]))

Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.8
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta precision: 99.9
Iris-setsuta p